### ISSUE TITLE
[AUR, Xfce] Settings icon in top right not visible

### ISSUE THREAD

**Issue by toprak** [dynobo/normcap#357] opened 2023-01-20 22:39 UTC
am I retarded I am searching it and cant find

**Comment by toprak** [comment] 2023-01-20 22:42
It was aur package's problem solved it via install it appimage

**Comment by tio-trom** [comment] 2023-01-28 23:02
Same here on XFCE + AUR. No tray icon. Is this an AUR issue tho? If so what could it be? Isn't the AUR package using the install guides from here? https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=normcap

**Comment by dynobo** [comment] 2023-01-29 07:02
@tio-trom , @toprak, thanks for reporting this issue!

I can reproduce this behavior with the current AUR package on Xfce. I'll investigate it...

In the meanwhile, could you try the AppImage as well, and report back if that works for you, too? That would help me. Thanks!

**Comment by dynobo** [comment] 2023-01-29 07:29
@tio-trom : I also noticed, that after running the AppImage _once_, the package install from AUR started to work, too. Now I'm having trouble reproducing the issue again... 

Could you please let me know, if you experience the same behaviour? That could indicate that there is a problem with the settings-initialization...

**Comment by tio-trom** [comment] 2023-01-29 12:52
Yes indeed. If I use the appimage once then I use the AUR, the settings icon is visible. But would be good to fix the AUR package somehow.

**Comment by dynobo** [comment] 2023-01-29 12:57
@tio-trom, thanks for the information! 

Yes, I'll definitely try to fix the issue also for the AUR package!

**Comment by tio-trom** [comment] 2023-01-29 12:59
Awesome! By the way I plan to include this package as default on TROMjaro - https://www.tromjaro.com/ - a Manjaro spin I have created. So we will debug as much as possible whatever is needed.

**Comment by dynobo** [comment] 2023-01-29 14:32
I identified the root cause: Just the icon is missing in the AUR package :grin:
If I hover the correct spot (when the cursor changes), I can open the settings menu and everything.

I very soon (today?) release a new major version which also overhauls icon management, so I don't think there's need to adjust the AUR package. The bugfix will just fix with the next release.

I'll leave this issue open until it's confirmed that the next v0.4.0 release will work.

**Comment by tio-trom** [comment] 2023-01-29 14:35
oh haha, that's funny! Happens sometimes. Great that you found the mystery and thank you for your commitment to fix these things. Let me know if I should test anything further. Cheers!

**Comment by dynobo** [comment] 2023-01-29 14:48
@tio-trom Thanks. Actually, you already helped me a lot: Through your link I learned about TROM (and skimmed  [the book](https://www.tromsite.com/books/#flipbook-df_6562/1/)), and the whole idea resonates a lot with me... 
 
But this is quite off-topic of NormCap. If you'd like to connect: I recently joined mastadon as dynobo@home.social

**Comment by tio-trom** [comment] 2023-01-29 14:50
Awesome. I connected with you.

**Comment by dynobo** [comment] 2023-01-30 16:35
AUR package for 0.4.0 got released, and in my tests it worked. 

Closing this issue now, please feel free to reopen in case it occurs again.

**Closed by dynobo** 2023-01-30 16:35 UTC
Labels: bug

**Comment by tio-trom** [comment] 2023-01-30 17:44
Awesome! Thank you for your work!
