### ISSUE TITLE
Unable to Install v0.2.7; Repeatedly Encountering Error Code 2349.

### ISSUE THREAD

**Issue by caramelized-jd** [dynobo/normcap#146] opened 2021-09-27 13:34 UTC
I have attempted to install v0.2.7 via the NormCap-Windows.msi file two days ago and again today. I am repeatedly encountering the following error during setup: "The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2349."

I am installing the software to a 64-bit Windows 10 Pro for Workstations, Version 21H1, OS build 19043.1237, Windows Feature Experience Pack 120.2212.3530.0.

**Comment by dynobo** [comment] 2021-09-27 16:45
Thanks for the bug report, @caramelized-jd. Unfortunately I'm not yet able to reproduce the issue. Can you please provide additional info?:

1. Are you trying to update NormCap? (Do you already have an older version installed?)
2. If yes, which version? (You can find it e.g. in Windows under "Add/remove programs")
3. If no, can you please test if the installation of [NormCap v0.2.6](https://github.com/dynobo/normcap/releases/tag/v0.2.6) is works for you?
4. Do you have any additional information which might help? (E.g. is it a company PC, which might have additional restrictions/policies?)

Thanks!

**Comment by caramelized-jd** [comment] 2021-09-28 19:41
Hi Dynobo,

1. I was trying to perform a new install of NormCap The software was previously installed on that computer but was uninstalled at the time of the attempted installation. I do, incidentally, have v0.2.7 installed on my other computer.

3. I installed NormCap v0.2.6 just now on the first computer without issue. I then attempted to install v0.2.7 on top of it, but I received the error:

"The file 'fil031A22C80A0BAFDlEC497FFF32C6A933'
cannot be installed because the file cannot be found in
cabinet file 'product.cab'. This could indicate a network
error, an error reading from the CD-ROM, or a problem
with this package."

Thank you,

JD

**Comment by dynobo** [comment] 2021-10-19 18:58
Hi @caramelized-jd , 

today I got hands on another Windows machine and tried to reproduce the issue, still without any luck. 

Could you please create a log file of the installation?
1. Download the [NormCap-Windows.msi](https://github.com/dynobo/normcap/releases/tag/v0.2.7)
2. Open a command prompt and navigate to the folder of the downloaded msi-file
3. Start the NormCap installer with the following command: 
   `msiexec /i NormCap-Windows.msi /l*v install.log`
4. Be patient until the installer window appears. Then click through to install.
5. Attach the new file `install.log` to a new Comment in this issue. (Please _attach_ the file itself and do not try to embed the text as comment, because it is fairly huge!).

Thanks, dynobo.

**Comment by dynobo** [comment] 2021-10-31 09:45
> Please find the log file attached to this message.

I can't see a log attached. Maybe something went wrong with the upload?

**Comment by dynobo** [comment] 2022-03-18 17:23
Lots of changes happened in the meantime. Closing this ticket for now.
Please feel free to re-open, in case this is still an issue with the latest release.

**Closed by dynobo** 2022-03-18 17:23 UTC
