### ISSUE TITLE
Error in v0.4.2

### ISSUE THREAD

**Issue by glocalglocal** [dynobo/normcap#454] opened 2023-05-31 13:01 UTC
I just updated from v0.4.1 to v0.4.2 using `NormCap-0.4.2-x86_64-Windows.msi` and now I am getting the following error on run: 

> Traceback (most recent call last):
  File "\app\normcap\__main__.py", line 3, in <module>
    from normcap.app import main
  File "\app\normcap\app.py", line 7, in <module>
    from PySide6 import QtCore, QtWidgets
ImportError: DLL load failed while importing QtCore: The specified module could not be found.

Windows 10, 64 bit

**Comment by qomhmd** [comment] 2023-05-31 20:57
Also, the same log is the case for me after updating. Running Windows 10.

> Traceback (most recent call last):
  File "\app\normcap\\_\_main\_\_.py", line 3, in \<module\>
    from normcap.app import main
  File "\app\normcap\app.py", line 7, in \<module\>
    from PySide6 import QtCore, QtWidgets
ImportError: DLL load failed while importing QtCore: The specified module could not be found.

**Comment by dynobo** [comment] 2023-06-02 15:30
@glocalglocal , @qomhmd, could one of you please provide a debug log output? Just open a CMD terminal, run the two commands below and share it's output here in the issue.

```cmd
set QT_DEBUG_PLUGINS=1

%LOCALAPPDATA%\Programs\dynobo\NormCap\NormCap.exe -v debug
```

**Comment by dynobo** [comment] 2023-06-02 15:46
Oh, and could you also try a complete removal and reinstall, [as described here](https://github.com/dynobo/normcap/issues/452#issuecomment-1563065934)?

**Comment by qomhmd** [comment] 2023-06-02 16:38
I did this, and it works well.

> Oh, and could you also try a complete removal and reinstall, [as described here](https://github.com/dynobo/normcap/issues/452#issuecomment-1563065934)?

**Comment by glocalglocal** [comment] 2023-06-03 13:06
> @glocalglocal , @qomhmd, could one of you please provide a debug log output? Just open a CMD terminal, run the two commands below and share it's output here in the issue.
> 
> ```batchfile
> set QT_DEBUG_PLUGINS=1
> 
> %LOCALAPPDATA%\Programs\dynobo\NormCap\NormCap.exe -v debug
> ```

Here is the output: 

```
C:\Users\user\AppData\Local\Programs\dynobo\NormCap>Log started: 2023-06-03 14:01:09Z
PreInitializing Python runtime...
PythonHome: C:\Users\user\AppData\Local\Programs\dynobo\NormCap
PYTHONPATH:
- C:\Users\user\AppData\Local\Programs\dynobo\NormCap\python310.zip
- C:\Users\user\AppData\Local\Programs\dynobo\NormCap
- C:\Users\user\AppData\Local\Programs\dynobo\NormCap\app_packages
- C:\Users\user\AppData\Local\Programs\dynobo\NormCap\app
Configure argc/argv...
Initializing Python runtime...
Running app module: normcap
---------------------------------------------------------------------------
Application quit abnormally (Exit code -6)!
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "C:\Users\user\AppData\Local\Programs\dynobo\NormCap\app\normcap\__main__.py", line 3, in <module>
    from normcap.app import main
  File "C:\Users\user\AppData\Local\Programs\dynobo\NormCap\app\normcap\app.py", line 7, in <module>
    from PySide6 import QtCore, QtWidgets
ImportError: DLL load failed while importing QtCore: The specified module could not be found.
Traceback (most recent call last):
  File "\app\normcap\__main__.py", line 3, in <module>
    from normcap.app import main
  File "\app\normcap\app.py", line 7, in <module>
    from PySide6 import QtCore, QtWidgets
ImportError: DLL load failed while importing QtCore: The specified module could not be found.
```

**Comment by dynobo** [comment] 2023-06-03 17:46
Then this is indeed a duplicate of #452. I'm closing this one.

**Closed by dynobo** 2023-06-03 17:46 UTC
Labels: duplicate
