### ISSUE TITLE
Windows GUI settings not persisted

### ISSUE THREAD

**Issue by koverg70** [dynobo/normcap#136] opened 2021-08-18 05:01 UTC
I have downloaded the Hungarian traineddata file and put it in resources. The hun language is selectable in the settings. But each time I start the program (even if keep on system tray is on) the chages in language settings are gone, and have to set it up again.

**Comment by dynobo** [comment] 2021-08-18 07:44
Thanks for the problem report, @koverg70 . 

Can you please tell me a bit more about your setup?
Did you install NormCap (a) from the Python package (`pip install normcap`), or did you (b) used the pre-build release package (`NormCap-Windows.msi`), or are you (c) working with the source repository?

**Comment by dynobo** [comment] 2021-12-27 19:22
In the latest [v0.2.10](https://github.com/dynobo/normcap/releases/tag/v0.2.10) I fixed an issue that could have caused such an issue. To do you want to try the new version and report back, if the issue is still there for you? Thanks!

**Comment by dynobo** [comment] 2022-02-24 20:48
Closing for now. Please reopen, if the issue persists.

**Closed by dynobo** 2022-02-24 20:48 UTC
