### ISSUE TITLE
normcap doesnt recognize and copy text

### ISSUE THREAD

**Issue by chbo70** [dynobo/normcap#182] opened 2022-02-21 12:32 UTC
i just setup my arch linux and installed normcap, after starting the app i tried to copy a text but i get an error message. 

![image](https://user-images.githubusercontent.com/96340581/154955697-f1ba0458-00ff-4dee-8530-6bd9be9f666f.png)

i tried reinstalling, however the problem remains

thanks in forward :)

**Comment by dynobo** [comment] 2022-02-21 17:11
Hi @chbo70, thanks for reporting this issue. 

Do you have Tesseract 5.x installed? (Check with `tesseract --version`). Because this seems like the same issue reported in #170.

**Comment by chbo70** [comment] 2022-02-21 17:17
@dynobo  yes it seems to be tesserat version 5.0.1.

**Comment by chbo70** [comment] 2022-02-21 17:20
should i downgrade to tesseract 4.x? if so how can i do it, because iam still relatively new to linux :)

**Comment by dynobo** [comment] 2022-02-21 19:46
If you're new Linux, I'd wouldn't recommend downgrading. I'd suggest one of the two options:

a) Use the AppImage version of NormCap: [Download the AppImage release](https://github.com/dynobo/normcap/releases/tag/v0.2.10), run `chmod +x NormCap-0.2.10-x86_64.AppImage` to make it executable, and then start NormCap with `./NormCap-0.2.10-x86_64.AppImage`.

b) Wait some more time. I'm currently working on an upgraded version, which will support Tesseract 5. An ok-ish Beta release of NormCap 0.3 should be ready next week, for a stable release I estimate another 1-2 weeks.

I'm going to close this issue as duplicate, but please feel free to comment here, if you need further assistance :-)

**Comment by dynobo** [comment] 2022-02-21 19:46
Duplicate of #170

**Closed by dynobo** 2022-02-21 19:46 UTC

**Comment by chbo70** [comment] 2022-02-21 20:15
@dynobo  thank you very much :) it works fine now i just set keybinding. cant wait for the new version and thanks for this awesome software
